### ISSUE TITLE
Spawning bosses as VIP won't work anymore

### ISSUE THREAD

**Issue by V1NAlt** [DFS-Servers/BugReportsAndSuggestions#83]
**Describe the bug**
The command /spawnboss doesn't respond even though it is in the VIP command list. The only thing it does is just show the command in chat. There is nothing in console relating to SM.

**To Reproduce**
Simple,
1. Join a server
2. Type in /spawnboss or look for it in /vipcommands.

**Expected behavior**
A small GUI should pop up allowing the user to spawn a boss.

**Screenshots or error logs**
Here's a small (probably useless in this case) blurb from the console.

Isabelle Vininator. :  /spawnboss
Isabelle Vininator. :  Still dead.
Punished "Venom" Snake :  oof
[DFS] Pure Bois suicided.

**Server Info (please complete the following information):**
 - Region: USA | VA
 - IP 198.24.171.83:27185

**Comment by Light08** [comment]
What map.

**Comment by V1NAlt** [comment]
trade_psykopat2, almost happens every map.

**Comment by Dispenz0r** [comment]
Will take a look when I get the chance

**Comment by Dispenz0r** [comment]
Should be fixed now, expect the command(s) to work properly when the servers are up.

Given a Community Box now, thanks for reporting!

**Comment by V1NAlt** [comment]
Never got a Community Box tho ever since the issue was fixed

**Comment by Dispenz0r** [comment]
I have given it, you should already have it.

Check your pack for an item called "Keyless Community Box".

**Comment by Light08** [comment]
When will you use the commands that I wrote just for you to distribute stuff to people with a message...

**Comment by V1NAlt** [comment]
I still don't seem to have it. Also, the amount of consumables I have seems a little off, too. I have 21 in total yet it says I have 23. Might have to make a new issue.
